# Generated by Django 2.1.2 on 2018-10-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_enter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enter',
            new_name='Entry',
        ),
    ]
